Introducción a Python
---------------------

¿Nuevo en Python? Vamos a configurar tu entorno.

.. toctree::
   :maxdepth: 2

   starting/which-python

- Instalar Python         

 .. toctree::
    :maxdepth: 1

    starting/install 
    starting/install/osx
    starting/install/win
    starting/install/linux



Escribir buen codigo en Python
-------------------------------

Esta parte de la guia se centra en buenas prácticas para escribir código en Python.

.. toctree::
   :maxdepth: 2

   writing/structure
   writing/style
   writing/reading
   writing/documentation
   writing/tests
   writing/logging
   writing/gotchas
   writing/license



Escenarios de aplicaciones en Python
------------------------------------

Esta parte de la guia se centra en herramientas y modulos para varios
escenarios.

.. toctree::
   :maxdepth: 2

   scenarios/client
   scenarios/web
   scenarios/scrape
   scenarios/cli
   scenarios/gui
   scenarios/db
   scenarios/network
   scenarios/admin
   scenarios/ci
   scenarios/speed
   scenarios/scientific
   scenarios/imaging
   scenarios/serialization
   scenarios/xml
   scenarios/json
   scenarios/crypto
   scenarios/clibs


Distribuir excelente código en Python
-------------------------------------

Esta parte del a guia se centra en distribuir tu código de Python.

.. toctree::
   :maxdepth: 2

   shipping/packaging
   shipping/freezing


Entornos de desarrollo de Python
--------------------------------

Esta parte de la guia se centra en entornos de desarrollo para Python y las
mejores herramientas para escribir el código.

.. toctree::
   :maxdepth: 2

   dev/env
   dev/virtualenvs
   dev/pip-virtualenv




Notas adicionales
-----------------

Esta parte de la guia se centra en información de contexto sobre Python y
después se centra en los siguientes pasos.

.. toctree::
   :maxdepth: 2

   intro/duction
   intro/community
   intro/learning
   intro/documentation
   intro/news

.. note::
   Notes defined within all diatonic and chromatic musical scales have been
   intentionally excluded from this list of additional notes. Additionally,
   this note.


--------------------------------------

Contribution notes and legal information (for those interested).

.. toctree::
   :maxdepth: 2

   notes/contribute
   notes/license
   notes/styleguide





